site_name: TODO (provide site_name in mkdocs.yml)
theme:
  name: material
plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
